[package]
name = "cargo-udeps"
version = "0.1.29"
authors = ["est31 <MTest31@outlook.com>", "Ryo Yamashita <qryxip@gmail.com>"]
description = "Find unused dependencies in Cargo.toml"
repository = "https://github.com/est31/cargo-udeps"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["cargo"]
categories = ["development-tools", "development-tools::cargo-plugins"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
vendored-openssl = ["cargo/vendored-openssl"]

[dependencies]
ansi_term = "0.12"
cargo = "0.62"
cargo-util = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "3.0", features = ["derive"] }
anyhow = "1.0"
wasm-bindgen-futures = "0.4.31"
web-sys = "0.3.58"

[dev-dependencies]
pretty_assertions = "1.0"
tempfile = "3.1"

[profile.dev]
debug = false


